### ISSUE TITLE
The Freegeoip service seems to not be available anymore

### ISSUE THREAD

**Issue by oxayotl** [ToX82/cookie-bar#125]
The https://freegeoip.app/json/ call fails because of CORS, and trying to open the URL redirects to an error page on https://ipbase.com.
It seems ipbase requires an API key for every call : https://ipbase.com/pricing/

**Comment by andresga** [comment]
Any news on this?

**Comment by ToX82** [comment]
Unfortunately I have no news, as every website owner would have to have their own API key to overcome this problem, and this would not be feasible.

The only temporary solution that comes to mind is to add the configuration parameter "nogeoip", so that the call is skipped altogether, thus not generating the warning.

Do not hesitate to suggest any service that does not have this limitation, if you can.

**Comment by oxayotl** [comment]
Thanks for the "nogeoip" suggestion! Will definitely use it, as I currently do not know any suitable service.

**Comment by ToX82** [comment]
I've finally found another geolocation service and I've updated the cookie-bar accordingly. Thank you ip-api.com!

**Comment by oxayotl** [comment]
Awesome! I still have a “mixed active content” error because the call is on http://ip-api.com/json/ even when my page is displayed through https. Apparently the https version is restricted to paying members?
