### ISSUE TITLE
Execution moment of blocking / preventing services

### ISSUE THREAD

**Issue by UisgeBeatha436** [ToX82/cookie-bar#88]
Hi,

Looking at the 'Preventive block' tab on the website, is see the option to verify setting of the cookie with f.i.:
```
<?php
if ($_COOKIE['cookiebar'] == "CookieAllowed") {
    // The user has allowed cookies, let's load our external services
}
?>
```
When is this script executed? As soon as the visitor hit the 'accept' button or when the **same** visitors visits the site within the time the cookie is valid?

Thanks.

**Comment by ToX82** [comment]
Hi,
that script is not run by the cookieBAR itself, it's just an example of what the website owner would want to do if he/she wants to check if the cookies have been accepted by the user or not.

What the cookieBAR does is to write a new cookie with a value that states the user's choice.

Then, in your website's source code, you can check if the user has accepted cookies (using one of those examples) and load external services or set your own cookies.

**Comment by cemerson** [comment]
On a related/similar note - I am unsure if I'm overcomplicating things or not.  Can anyone confirm this is the correct way to use CookieBar?

1. Include the Cookiebar JS on my website
2. Update my website code everywhere tracking or third party cookies are created with the appropriate user-values from: Cookiebar's cookies:  "cookiebar", "cookiebar-tracking" or "cookiebar-third-barty"
3. When user(s) visit my website their Cookiebar decision(s) will then affect all cookie/tracking behavior across the entire site

Could someone please confirm that step #2 above is indeed required? Asking because I see in the README it says this is a "_drop in and forget_" plugin - but I'm not sure if that's implying if extra coding in step #2 is still necessary or it isn't.  Based on what I see in the Dev Tools it does seem like the extra coding *is* required but I just want to make sure.

**Comment by bbalm** [comment]
Step 2 is indeed needed! 

More detailed explanation: it is needed if you want to use Cookiebar to provide actual opt-in, rather than just informing the user cookies are used on the website; but providing opt-in functionality is currently what you should do to comply to regulations across the world, e.g. EU GDPR)

**Comment by cemerson** [comment]
Thank you @bbalm! After a while staring at cookies too long you start to question reality ... so I definitely needed someone to confirm for me. Thank you 🙏🏻
